### ISSUE TITLE
Missing which URL do call

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/alfredudu-paycheck#1]
It is missing which end point (url) to call and calculate salary tax at https://github.com/univas-first-exam/alfredudu-paycheck/blame/master/asset/js/SalaryService.js

**Comment by alfredudu** [comment]
Fix with commit 2:

https://github.com/univas-first-exam/alfredudu-paycheck/commit/359a3454d2fad40fd70ce605f04f46dfea984577

**Comment by edysegura** [comment]
Hi @alfredudu! It still missing the url param

**Comment by alfredudu** [comment]
Fix Edy 

https://github.com/univas-first-exam/alfredudu-paycheck/blob/1b48e237202e04f010fef00743db82d981709d7c/asset/js/SalaryService.js#L6

**Comment by edysegura** [comment]
Great!!
