### ISSUE TITLE
Sintaxe error

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/alfredudu-paycheck#2]
There is a syntax error that is not allowing to use the application properly.

![image](https://cloud.githubusercontent.com/assets/5324414/10747401/d27e9728-7c3b-11e5-8b47-86f25ba163fc.png)

**Comment by alfredudu** [comment]
Fix with commit 3:
https://github.com/univas-first-exam/alfredudu-paycheck/commit/6ab681763e30bae084c1d572098d915077535edf
