### ISSUE TITLE
Use comma instead of colon

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/alfredudu-paycheck#3]
To use one var to multiple variable declaration use comma instead of colon at https://github.com/univas-first-exam/alfredudu-paycheck/blob/master/asset/js/SalaryController.js#L18

![image](https://cloud.githubusercontent.com/assets/5324414/10746890/36f6eaa8-7c36-11e5-82fd-d2135d9668e6.png)

**Comment by alfredudu** [comment]
Fix with commit 4;
https://github.com/univas-first-exam/alfredudu-paycheck/commit/4280cfde293d1354a5d18ac8628f5a3caa70c528

**Comment by edysegura** [comment]
Nice one!!!
